// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDINTDU5SVKhwY3avUx0iqk22WDyKRi744',
    appId: '1:557588453189:web:00da1b4883f89803e1502c',
    messagingSenderId: '557588453189',
    projectId: 'vs-mssv2',
    authDomain: 'vs-mssv2.firebaseapp.com',
    storageBucket: 'vs-mssv2.firebasestorage.app',
    measurementId: 'G-N50NG92MB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZbjrmLC46tVu6EfdQQZROv6QSlLO3qPM',
    appId: '1:557588453189:android:79fdba6964e5e0e3e1502c',
    messagingSenderId: '557588453189',
    projectId: 'vs-mssv2',
    storageBucket: 'vs-mssv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJPi3Pz2xUGuGy6iDkExJbJhAbf-P806Y',
    appId: '1:557588453189:ios:6cb8c2e80f6c0bf2e1502c',
    messagingSenderId: '557588453189',
    projectId: 'vs-mssv2',
    storageBucket: 'vs-mssv2.firebasestorage.app',
    iosBundleId: 'com.example.ltudLab',
  );
}
